### ISSUE TITLE
scatterplot matrix visualization pushed off screen

### ISSUE THREAD

**Issue by superlib** [Kitware/candela#387] opened 2016-09-13 14:37 UTC
With a scatterplot matrix, if I choose a data column with a large number of discrete entries as the 'Color' attribute, the visualization shifts too far up the page and is no longer fully visible.

**Comment by ronichoudhury** [comment] 2016-09-13 14:43
Can you post the exact example (with screencap) where you noticed this?

**Comment by superlib** [comment] 2016-09-13 14:52
This was using the Cars dataset within Resonant Laboratory. The issue occurs using the Economy or Name column as the Color attribute, and any other column as the Field attribute.
It occurs whether or not you apply filters to the Economy | Name column.

![scatterplot_bug](https://cloud.githubusercontent.com/assets/21109376/18478663/0fb3c53e-79a0-11e6-9a92-2d0c4df19930.png)

**Comment by ronichoudhury** [comment] 2016-10-04 16:03
Dupe of #200

**Closed by ronichoudhury** 2016-10-04 16:03 UTC
